// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD11bQrTxO1UpxSnD5MZCxPMppkEIFJqYg',
    appId: '1:739896266270:web:041d541a009543217d680f',
    messagingSenderId: '739896266270',
    projectId: 'afz-restaurant',
    authDomain: 'afz-restaurant.firebaseapp.com',
    storageBucket: 'afz-restaurant.firebasestorage.app',
    measurementId: 'G-CCCNL057KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH30Xho5oTZ7uC665sGiCQ55cMVHHpEck',
    appId: '1:739896266270:android:250937c6451c65717d680f',
    messagingSenderId: '739896266270',
    projectId: 'afz-restaurant',
    storageBucket: 'afz-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVot4dL4iSweTeUFnV7NmBl3a3CV3VAqY',
    appId: '1:739896266270:ios:f2c5a8eb294532177d680f',
    messagingSenderId: '739896266270',
    projectId: 'afz-restaurant',
    storageBucket: 'afz-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.afzRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVot4dL4iSweTeUFnV7NmBl3a3CV3VAqY',
    appId: '1:739896266270:ios:f2c5a8eb294532177d680f',
    messagingSenderId: '739896266270',
    projectId: 'afz-restaurant',
    storageBucket: 'afz-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.afzRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD11bQrTxO1UpxSnD5MZCxPMppkEIFJqYg',
    appId: '1:739896266270:web:d8adb55ec2159e9f7d680f',
    messagingSenderId: '739896266270',
    projectId: 'afz-restaurant',
    authDomain: 'afz-restaurant.firebaseapp.com',
    storageBucket: 'afz-restaurant.firebasestorage.app',
    measurementId: 'G-J2HH90TY6H',
  );
}
